### ISSUE TITLE
pip install failure

### ISSUE THREAD

**Issue by ea42gh** [awesome-panel/panel-chemistry#13]
I was following the instructions from video 0.1:
```
git clone https://github.com/MarcSkovMadsen/panel-chemistry.git
 cd panel-chemistry
 conda create --name panel-chemistry
 conda activate panel-chemistry
 pip install -e .[all]
```

this resulted in an error for `pywinpty`
```
 Cargo, the Rust package manager, is not installed or is not on PATH.
    This package requires Rust and Cargo to compile extensions.
```

**Comment by ea42gh** [comment]
it triggered on `pywinpty` during execution of `pip install -e .[all]`
Installing rust and rerunning the command succeeds with windows.

On linux, I had rust installed to begin with. No issues

**Comment by MarcSkovMadsen** [comment]
I don't understand where the `pywinpty` requirement is coming from. I will investigate.

**Comment by MarcSkovMadsen** [comment]
![image](https://user-images.githubusercontent.com/42288570/120068153-89c99080-c07f-11eb-842c-95d99f351277.png)

I am on Windows 10 and python 3.8.4. I definitely don't have Rust installed.

Do you know what triggers the rust dependency?

**Comment by ea42gh** [comment]
Hmm, tried to uninstall rust. Used conda update all
(upgrade, downgrade, regrade ...grade - I really dislike conda...)
activated panel-chemistry and tried
` pip install --upgrade --force-reinstall -e .[all] `

This now fails with a permission error.....

`pip install -e.[all]`  succeeds.

I have no idea how to duplicate my previous problem with rust! Sigh...

**Comment by MarcSkovMadsen** [comment]
I will close this one. If it is still an issue please reopen.
