### ISSUE TITLE
Add NGL Molecule Viewer

### ISSUE THREAD

**Issue by MarcSkovMadsen** [awesome-panel/panel-chemistry#15]
PyHDX has an existing NGL Molecule Viewer which is ok to copy or get inspiration from.

https://github.com/Jhsmit/PyHDX/blob/master/dev/bokeh_extension.py

https://twitter.com/Jhsmit_/status/1398233190519693317

![image](https://user-images.githubusercontent.com/42288570/120091312-28023880-c10a-11eb-91b5-d238bf18ef9d.png)

**Comment by MarcSkovMadsen** [comment]
I also have a one way communicating ngl viewer here https://github.com/MarcSkovMadsen/awesome-panel-extensions/blob/master/awesome_panel_extensions/widgets/ngl_viewer.py

**Comment by Jhsmit** [comment]
The code you reference is a standalone working example but the code in this folder is more our testing/playground folder.
The current implementation in PyHDX is found here:
typescript: https://github.com/Jhsmit/PyHDX/blob/master/pyhdx/panel/ngl_viewer.ts
widget: https://github.com/Jhsmit/PyHDX/blob/12fc2b5f67200885706226823bd8e1f46e3b5db1/pyhdx/panel/widgets.py#L130

The two-way NGL viewer as bokeh extension was done by @sebaztiano

**Comment by MarcSkovMadsen** [comment]
With inspiration from the PR provided by @Jhsmit I started working on this here https://github.com/MarcSkovMadsen/panel-chemistry/tree/ngl_viewer
